version: '2'
services:
  proxy_pool:
    image: harbor.vocoor.com/ci/proxy-pool:latest
    container_name: proxy-pool
    ports:
      - "5010:5010"
    environment:
      DB_CONN: "redis://:lilishop@192.168.2.130:6379/10"
    restart: unless-stopped